## Gerar números da Mega Sena




In [ ]:
import numpy as np

print("Entre com a quantidade de jogos a fazer:")
jogos = int(input())

print("Você escolheu fazer {0} jogos.".format(jogos))
print("Pressione enter para prosseguir com a geração dos jogos.")
continua = input()

megaSena = np.random.randint(1,60,size=(jogos,6))
print(megaSena)

In [16]:
# Sem repetição - resolvido

import numpy as np

conjunto = np.array([n for n in range(1,61)])
#print(conjunto)

print("Entre com a quantidade de jogos a fazer:")
jogos = int(input())

print("Você escolheu fazer {0} jogos.".format(jogos))
print("Pressione enter para prosseguir com a geração dos jogos.")
continua = input()

megaSena = np.random.choice(conjunto,size=(jogos,6)) # método choice recebe uma lista e retorna valores aleatórios da amostra, sem repetição.
print(megaSena)

Entre com a quantidade de jogos a fazer:
5
Você escolheu fazer 5 jogos.
Pressione enter para prosseguir com a geração dos jogos.

[[ 3 27  9 24 36 51]
 [32 54  5 10 15 60]
 [26 53 34 26 18 55]
 [45 47 44 41  4 27]
 [12 36 41 51 11 35]]


Para gerar números não repetidos em cada jogo:
https://stackoverflow.com/questions/8505651/non-repetitive-random-number-in-numpy
e isso
https://numpy.org/doc/stable/reference/random/index.html#random-quick-start
e isso
https://www.xspdf.com/resolution/52947746.html