# NumPy

## Numerical Python

Biblioteca de código aberto criada em 2006, é é um pacote fundamental extensivamente empregado para computação numérica e científca de alta performance e velocidade em Python. Escrita em linguagem C, é a implementação de estruturas de dados do tipo arrays preferida em Python, fornecendo um tipo de array de alta performance chamado de **ndarray**.

As operações sobre arrays do NumPy chegam a ser até duas ordens de magnitude mais rápidas do que om o emprego de listas comuns em Python, o que certamente é uma grande vantagem quando pensamos em grandes volumes de dados a serem manipulados e analisados, por exemplo em aplicações para Big Data e Computação Numérica.

O NumPy trabalha com um objeto de array de N dimensões poderoso chamado de *ndarray* (N-Dimensional Array / Array de N Dimensões), e possui diversas funções e métodos para sua manipulação, além de ouros tipos de objetos como masked arrays e matrizes, dos quais trataremos futuramente.

Muitas bibliotecas populares e altamente importantes dependem do NumPy para operar, como por exemplo as bibliotecas SciPy (para computação científica), Pandas (Análise de Dados), OpenCV, Scikit-learn e Keras (Machine Learning / Deep Learning), entre centenas de outras bibliotecas.


## Módulo NumPy

O módulo NumPy fornece diversas funções para criação e manipulação de arrays. Os elementos em um array podem ser acessados por meio de seus números de índice (posição), e os índices de arrays iniciam sua contagem em 0, de modo que o primeiro elemento armazenado é o elemento de índice 0, o segundo elemento é o elemento de índice 1, e assim por diante.

In [ ]:
# Criar arrays a partir de dados existentes

# Importar o módulo numpy. Recomenda-se importá-lo como "np", de acordo com a documentação oficial, para padronização.
import numpy as np

# Criar um array (objeto ndarray) de nome "números" a partir de uma lista de valores com o método np.array()
números = np.array([4,8,16,32,64,128])

# Opcionalmente, podemos especificar o tipo de dado dos objetos do array com um segundo parâmetro:
# números = np.array([4,8,16,32,64,128], np.int16) # Elementos do tipo Int 16 bits.

# Ver o tipo do objeto criado
print(type(números))

# Ver o conteúdo do array (valores alinhados à direita, ocupando o mesmo número de casas de acordo com o maior número presente)
print(números)

# Ver elementos específicos no array por meio de seus índices
print(números[0]); print(números[1]); print(números[2]); print(números[-1])

## Tipos de Dados comuns no NumPy

| Tipo NumPy                | Descrição                                                                             |
|---------------------------|---------------------------------------------------------------------------------------|
| np.int8                   | Byte (-128 a 127)                                                                     |
| np.int16                  | Inteiro (-32768 a 32767)                                                              |
| np.int32                  | Inteiro (-2147483648 a 2147483647)                                                    |
| np.int64                  | Inteiro (-9223372036854775808 a 9223372036854775807)                                  |
| np.uint8                  | Inteiro sem sinal (0 a 255)                                                           |
| np.uint16                 | Inteiro sem sinal (0 a 65535)                                                         |
| np.uint32                 | Inteiro sem sinal (0 a 4294967295)                                                    |
| np.uint64                 | Inteiro sem sinal (0 a 18446744073709551615)                                          |
| np.float32                | Ponto flutuante de 32 bits                                                            |
| np.float64 np.float_      | Double                                                                                |
| np.complex64              | Número complexo, representado por dois floats de 32 bits (partes real e imaginária)   |
| np.complex128 np.complex_ | Número complexo de precisão dupla (corresponde à precisão do tipo complexo em Python) |

In [ ]:
# Criar um array bidimensional a partir de uma matriz (lista de duas dimensões)

matriz = np.array([[1,4,5],[3,5,2],[5,6,0]]) # Cada colchete aninhado representa uma dimensão do array
print(matriz)

# Criar array de três dimensões

In [1]:
import numpy as np

# Criar um array tridimensional (lista de três dimensões)

# Cada colchete aninhado representa uma dimensão do array
cubo = np.array([[[1,4,7],[3,5,2]],[[5,6,0],[7,4,1]],[[2,8,8],[0,3,6]]])
print('Array tridimensional:\n ', cubo)

Array tridimensional:
  [[[1 4 7]
  [3 5 2]]

 [[5 6 0]
  [7 4 1]]

 [[2 8 8]
  [0 3 6]]]


In [2]:
# Visualizar elementos específicos do cubo (array tridimensional)
print('\nItem na posição 0,0,0: ', cubo[0,0,0])
print('Item na posição 1,0,0: ', cubo[1,0,0])
print('Item na posição 2,0,0: ', cubo[2,0,0])


Item na posição 0,0,0:  1
Item na posição 1,0,0:  5
Item na posição 2,0,0:  2


In [3]:
# Número de dimensões do array:
print('Número de dimensões do array cubo: ', cubo.ndim)

# Dimensões do array:
print('Tamanho do array cubo: ', cubo.shape)

# Número total de elementos do array:
print('Total de elementos do array cubo: ', cubo.size)


Número de dimensões do array cubo:  3
Tamanho do array cubo:  (3, 2, 3)
Total de elementos do array cubo:  18


In [4]:
import numpy as np

# Outro array tridimensional: 2x3x3 (dois blocos, três linhas e três colunas)

tri = np.array([ [ [0,0,0],[1,1,1],[2,2,2] ],[ [4,4,4],[5,5,5],[6,6,6] ] ])
print(tri)
            

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]]


In [5]:
# Imprimir os elementos do array usando iteração com laços for

for i in range(2):
    for j in range(3):
        for k in range(3):
            print('Posição {0},{1},{2}: {3}'.format(i,j,k,tri[i][j][k]))

Posição 0,0,0: 0
Posição 0,0,1: 0
Posição 0,0,2: 0
Posição 0,1,0: 1
Posição 0,1,1: 1
Posição 0,1,2: 1
Posição 0,2,0: 2
Posição 0,2,1: 2
Posição 0,2,2: 2
Posição 1,0,0: 4
Posição 1,0,1: 4
Posição 1,0,2: 4
Posição 1,1,0: 5
Posição 1,1,1: 5
Posição 1,1,2: 5
Posição 1,2,0: 6
Posição 1,2,1: 6
Posição 1,2,2: 6


## ------------------------------------------------------------- ##

In [ ]:
# Verificar o tipo de elemento do array: atributo dtype
números.dtype

In [ ]:
# Determinar o número de dimensões de um array: atributo ndim

print('Dimensões do array números: ', números.ndim)
print('Dimensões da matriz: ', matriz.ndim)

In [ ]:
# Determinar as dimensões de um array: atributo shape (tamanho do array)

print('Tamanho do array números: ', números.shape)
print('Tamanho da matriz: ', matriz.shape)

In [ ]:
# Número total de elementos de um array: atributo size
print('Total de elementos do array números: ', números.size)
print('Total de elementos da matriz: ', matriz.size)

In [ ]:
# Tamanho dos elementos de um array (número de bytes necessário para armazenamento): atributo itemsize
print(números.itemsize)
print(matriz.itemsize)

In [ ]:
# Iteração: iterar por um array multidimensional como se ele fosse unidimensional - atributo flat
for i in matriz.flat:
    print(i, end=' ') # end=' ' é usado para mostrar os valores em uma única linha, em vez de um por linha

In [ ]:
x = np.array([[1,2,3],[6,4,2]], np.int16)
for i in x.flat:
    print(i, end=' ')

In [ ]:
# Criar array unidimensional e transformá-lo em bidimensional: método reshape
print(np.arange(10,50,2).reshape(5,4)) # array 5x4

## Preencher arrays com valores específicos

Podemos preencher arrays com valores específicos, repetidos ou diferentes, ou ainda valores gerados aleatoriamente.

In [16]:
import numpy as np

# Criar um array com os números pares de 0 a 100:
pares = np.array([n for n in range(0,101,2)])
print(pares)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


### Preencher arrays com zeros, uns ou valores específicos

Com as funções *zeros*, *ones* e *full* podemos criar arrays preenchidos automaticamente com zeros, uns ou um valor numérico especificado, respectivamente.

Os métodos zeros e ones produzem valores do tipo float64 por padrão, mas podemos alterar o tipo de dado se necessário.

In [17]:
# Criar array com 10 elementos iguais a 0
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
# Criar array com 15 elementos iguais a 1
print(np.ones(15))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
# Criar array com 8 elementos iguais a 12 (int)
print(np.full(8,12))  # primeiro argumento: núm. de elementos.

[12 12 12 12 12 12 12 12]


In [20]:
# Criar array com 10 elementos iguais a 0, tipo inteiro
print(np.zeros(10, dtype=int))

# Criar array com 15 elementos iguais a 1, tipo inteiro
print(np.ones(15, dtype=int))

# Criar array com 8 elementos iguais a 12, tipo ponto flutuante
print(np.full(8,12, dtype=float))  # primeiro argumento: núm. de elementos.

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[12. 12. 12. 12. 12. 12. 12. 12.]


In [21]:
# Criar array bidimensional 2x5 preenchido com zeros, tipo inteiro:
print(np.zeros((2, 5),dtype=int))

[[0 0 0 0 0]
 [0 0 0 0 0]]


### Criar array a partir de faixas de valores: métodos *arange* e *linspace*

In [22]:
# Criar array a partir de faixas de valores: método arange

# Array de 10 elementos, números de 0 a 9
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [23]:
# Array de 10 elementos float, números de 0 a 9
print(np.arange(10.))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [24]:
# Array com valores no intervalo de 5 a 15
print(np.arange(5,16))

[ 5  6  7  8  9 10 11 12 13 14 15]


In [25]:
# Array com os números pares de 50 até 1
print(np.arange(50, 1, -2))

[50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10  8  6  4
  2]


In [26]:
# Criar array com valores de ponto flutuante com o método linspace

print(np.linspace(0.0,2.0,num=5))
# primeiro argumento: valor inicial
# segundo argumento: valor final
# terceiro argumento (num): quantidade de itens a gerar

[0.  0.5 1.  1.5 2. ]


### Array com valores aleatórios - Métodos *rand* e *randint*

In [27]:
# Criar e preencher array com valores aleatórios

import numpy as np

# Array de 10 elementos entre 0 e 1
a = np.random.rand(10)
print(a)

[0.07418479 0.95672716 0.19361192 0.32394591 0.29980946 0.20812523
 0.92100292 0.49129843 0.78413243 0.07830975]


In [28]:
# Array bidimensional 3x3 com valores aleatórios
c = np.random.rand(3,3)
print(c)

[[0.56700019 0.56581178 0.47336097]
 [0.5626577  0.75670315 0.8608974 ]
 [0.71296439 0.09674716 0.95800157]]


In [32]:
# Gerar um número aleatório inteiro entre 0 e 8 com random.randint
print('Número aleatório:', np.random.randint(9))

Número aleatório: 3


In [35]:
# Array unidimensional com 10 números aleatórios inteiros entre 10 e 20
b = np.random.randint(10,21,size=10)
print(b)

[13 17 16 16 16 12 18 15 14 12]


In [43]:
# Array bidimensional 4x5 com números aleatórios inteiros entre 1 e 30
d = np.random.randint(1,101,size=(10,10))
print(d)

[[ 50  55  74  93  77  42  71  69  44  50]
 [ 13  13  79  50  82  75  91  11  79  26]
 [ 76  47  59  79  20  58  30  20  22  36]
 [ 13  81   9  77  34  21   3  91  21  29]
 [ 88  38  76 100   9  18  20  11  39  94]
 [ 45  23  81  13  59   1  13  44  36  33]
 [ 48  93  82  99  97  39  94  23  41  86]
 [ 17  21  65  52  85  87  15  75  50  75]
 [ 61  35  17  52  71  32  29  61  21  62]
 [ 66  19  78  47  92  23  52  58  81  68]]


## Verificar performance de arrays NumPy vs listas

Usando o comando **%timeit magic** do IPython, que contabiliza a duração média de operações.

In [ ]:
# Medir tempo para criação de uma lista comum com 10 milhões de itens
import random

%timeit teste = [random.randrange(1,10) for i in range(0, 10000000)]

In [ ]:
# Medir tempo para criação de um array NumPy com 10 milhões de itens
import numpy as np

%timeit teste = np.random.randint(1,10,10000000)

In [ ]:
# Medir tempo para criação e soma de valores de uma lista comum com 5 milhões de itens

%timeit sum([n for n in range(5000000)])

In [ ]:
# Medir tempo para criação e soma de valores de um array NumPy com 5 milhões de itens

%timeit np.arange(5000000).sum()

## Operações aritméticas com arrays

É possível realizar diversas operações aritméticas sobre arrays, com o emprego de operadores variados. Vamos estudar aritmética simples com alguns exemplos de operações entre arrays e valores escalares, e entre arrays de mesmas dimensões.

Iniciamos criando um array para testes, de nome valores, contendo números de 1 a 10.

In [ ]:
import numpy as np

valores = np.arange(1,11)
print(valores)

In [ ]:
# Vamos realizar operações aritméticas com os valores do array: multiplicação e exponenciação

print(valores * 5)
print(valores ** 3)

# As operações são efetuadas para cada valor presente no array, individualmente. Essa operação se chama broadcasting.
# O array em si permanece inalterado:
print(valores)

# Porém é modificado por operações cumulativas, como incremento:
valores += 10
print(valores)

### Operações aritméticas entre arrays

É possível efetuar operações aritméticas entre arrays que tenham as mesmas dimensões (shape). Por exemplo, vamos efetuar a multiplicação entre dois arrays unidimensionais de 4 elementos cada.

O resultado será um novo array formado pela multiplicação de cada elemento no primeiro array pelo elemento na posição correspondente no segundo array:

In [ ]:
# Multiplicação de arrays

val1 = np.array([2,4,6,8])
val2 = np.array([1,2,3,4])

print(val1 * val2)

### Efetuar operações matemáticas comuns

Podemos também efetuar diversas operações matemáticas comuns sobre os elementos de um array, como determinar o maior e menor valor, somatório, média, valores estatísticos, etc.

Considere o seguinte exemplo:

In [ ]:
# Aplicando funções sobre um array

val = np.array([2,4,5,6,8,10,11])

# Somatório do array
print(val.sum())

# Média aritmética dos valores do array
print(val.mean())

# Maior valor presente no array
print(val.max())

# Menor valor presente no array
print(val.min())

# Desvio-padrão do array
print(val.std())

# Variância do array
print(val.var())

## Operações em linhas ou colunas

É possível efetuar operações em linhas ou colunas inteiras de um array multidimensional, bastando para isso especificar o eixo desejado por meio do parâmetro *axis*.

O valor 0 em axis representa colunas, ao passo que o valor 1 indica linhas.

Como exemplo, vamos considerar uma tabela de valores bidimensional como a que segue:

2 3 6
3 5 7
2 4 7
2 7 8

Desejamos conhecer o somatório de cada linha individual, e o valor médio de cada coluna. Para isso, faremos da seguinte forma:


In [ ]:
import numpy as np

matriz = np.array([[2,3,6],[3,5,7],[2,4,7],[2,7,8]])
print(matriz)

# Somatório de cada linha
print(matriz.sum(axis=1))

# Média aritmética de cada coluna
print(matriz.mean(axis=0))

## Calcular raiz Quadrada dos Elementos de um array

Podemos calcular a raiz quadrada de cada elemento de um array usando uma função universal, que é aplicada a cada elemento individualmente.

A função para cálculo de raiz quadrada é a função np.sqrt()

Vamos ao exemplo.

In [ ]:
# Calcular a raiz quadrada de cada elemento de um array

import numpy as np

valores = np.arange(10,101,5)  # números de 10 a 100, de 5 em 5
print(valores)

# Raiz de cada elemento do array:
print(np.sqrt(valores))

## Soma de arrays

De forma análoga, podemos somar dois arrays de mesma dimensão usando uma função universal: a função np.add().

Vejamos um exemplo.

In [ ]:
# Soma de arrays com função np.add()
import numpy as np

# Criar os dois arrays
val1 = np.arange(10,21)
print(val1)
val2 = np.arange(40,51)
print(val2)

# Relizar a soma e exibir o resultado
res = np.add(val1, val2)
print(res)


## Outras funções universais do NumPy

A biblioteca NumPy possui diversas funções universais disponíveis. Algumas delas estão listadas a seguir:

- Funções matemáticas: add, subtract, multiply, divide, remainder, exp, log, power
- Funções trigonométricas: sin, cos, tan, hypot, arcsin, arccos, arctan
- Manipulação de bits: bitwise_and, bitwise_or, bitwise_xor, invert, left_shift, right_shift
- Comparação: greater, greater_equal, less, less_equal, equal, not_equal, logical_and, logical_or, logical_xor, logical_not, minimum, maximum
- Ponto flutuante: floor, ceil, isinf, isnan, fabs, trunc


## Indexação e Fatiamento de arrays

Os índices de arrays iniciam sua contagem em 0, de modo que o primeiro elemento armazenado é o elemento de índice 0, o segundo elemento é o elemento de índice 1, e assim por diante.

In [ ]:
# Indexação e fatiamento de arrays unidimensionais (inicia indexação de zero)

import numpy as np

valores = np.array([2,5,8,0,12,9,11,5,7])
print(valores) # Mostra o array inteiro
print(valores[0]) # Primeiro elemento do array (índice 0)
print(valores[-1]) # Último elemento do array (índice -1)
print(valores[:3]) # três primeiros elementos do array
print(valores[2:5]) # do segundo ao quarto elemento (5 - 1), ou ainda, três elementos a partir do segundo (5 - 2)
print(valores[4:]) # Do quarto elemento até o final do array

In [ ]:
# Indexação e fatiamento de arrays bidimensionais (inicia indexação de zero)

import numpy as np

matriz = np.array([[3,5,7],[1,0,5],[7,2,8]])
print(matriz)

print(matriz[0,0]) # Mostrar elemento da primeira linha, primeira coluna
print(matriz[2,1]) # Mostrar elemento da linha 2, coluna 1
print(matriz[1]) # Linha 1 inteira 
print(matriz[0:2]) # Linhas 0 e 1
print(matriz[[0,2]]) # Linhas 0 e 2 - usar lista de índices
print(matriz[:,1]) # Coluna 1 inteira 
print(matriz[:,1:]) # Colunas 1 e 2 inteiras com fatiamento ou
print(matriz[:,[1,2]]) # Colunas 1 e 2 inteiras usando lista de colunas

## Copiar arrays: Shallow Copies (Views) e Deep Copies

Um objeto do tipo view é um objeto que "enxerga" os dados em outros objetos, em vez de possuírem suas próprias cópias dos dados. Diversos métodos dos arrays e operações de fatiamento criam views dos dados dos arrays.

O método view retorna um novo objeto array com uma visualização dos dados do array original (como um "ponteiro" para o array)

In [ ]:
# Criar array e view do array
import numpy as np

valores = np.array([1,3,5,7,9,11])
print('Array original:',valores)

# Criar view
valview = valores.view()
print('Conteúdo da view:',valview)

# Confirmar que os dois arrays são objetos diferentes com função id
print('Array: ',id(valores),' View: ', id(valview))

# Como ambos os objetos se referem ao mesmo conjunto de valores, se os dados forem modificados em um a modificação será vista pelo outro
valores[0] = 13
print('\nArray original:',valores)
print('Conteúdo da view:',valview)

# De forma análoga:
valview[5] = 21
print('\nArray original:',valores)
print('Conteúdo da view:',valview)

## Deep Copies

Views são objetos de array separados, e por conta disso economizam memória ao compartilhar o mesmo conjunto de dados de outros arrays. 

Porém, ao compartilhar objetos mutáveis, às vezes precisamos criar uma deep copy, que consiste em um objeto array que é uma cópia de outro array, porém independente - sem fazer referência ao mesmo conjunto de dados, ams efetivamente copiando os dados de um array para outro. Uma aplicação de exemplo de deep copies é em programação multicore, na qual partes separadas de uma aplicação podem tentar modificar dados ao mesmo tempo, com o risco ed corromper dados.

Uma deep copy é, assim, como se fosse uma espécie de "backup de array", por analogia.

Para criar uma deep copy usamos o método de array copy.

In [ ]:
# Criar array e deep copy do array
import numpy as np

valores = np.array([1,3,5,7,9,11])
print('Array original:',valores)

# Criar cópia
valview = valores.copy()
print('Conteúdo da cópia:',valview)

# Confirmar que os dois arrays são objetos diferentes com função id
print('Array: ',id(valores),' Deep copy: ', id(valview))

# Como ambos os objetos são separados, se os dados forem modificados em um a modificação não afetará o outro
valores[0] = 13
print('\nArray original:',valores)
print('Conteúdo da cópia:',valview)

# De forma análoga:
valview[5] = 21
print('\nArray original:',valores)
print('Conteúdo da cópia:',valview)

## Método reshape

O método reshape retorna uma view (shallow copy) de um array com as suas dimensões alteradas. Por exemplo, podemos transformar um array bidimensional em um array unidimensional. O método reshape não modifica o array original.

In [ ]:
# Método reshape - exemplo

import numpy as np

matriz = np.array([['A','B','C'],['H','I','J'],['X','Y','Z']])
print('Array bidimensional original:\n',matriz)

# Aplicar método reshape, retornando a matriz como array unidimensional de 9 elementos
print('\nReshape:',matriz.reshape(1, 9))

# Verificar que o array original permanece inalterado
print('\nArray bidimensional original:\n',matriz)

## Método resize

De forma análoga ao método reshape, altera as dimensões de um array. Porém, o método resize altera as dimensões do array original. Por exemplo, podemos transformar um array bidimensional em um array unidimensional.

In [ ]:
# Método resize - exemplo

import numpy as np

matriz = np.array([['A','B','C'],['H','I','J'],['X','Y','Z']])
print('Array bidimensional original:\n',matriz)

# Aplicar método resize, transformando a matriz em array unidimensional de 9 elementos
matriz.resize(1, 9) # Método não retorna valores, age diretamente sobre o array

# Verificar que o array original foi alterado
print('\nArray bidimensional original:\n',matriz)

## Métodos flatten e ravel

Podemos tomar um array multidimensional e "achatá-lo" em um array de uma dimensão usando os métodos **flatten** e **ravel**.

O método flatten opera com deep copies (novo array independente)
O método ravel opera com shallow copies (views).

In [ ]:
# Método flatten

import numpy as np

# Criar array bidimensional 4x3 de exemplo
matriz = np.array([['A','B','C'],['H','I','J'],['P','Q','R'],['X','Y','Z']])
print('Array bidimensional original:\n',matriz)

# Aplicar método flatten e criar array unidimensional independente
achatadoF = matriz.flatten()

# Visualizar array achatado e original
print('\nArray achatado:',achatadoF)
print('\nArray bidimensional original:\n',matriz) # Array original não é alterado

# Alterar dados no array original e verificar se são alterados no array achatado
matriz[0,0] = 'K'
print('\nArray bidimensional original:\n',matriz) # Dado na posição 0,0 alterado
print('\nArray achatado:',achatadoF) # Dados inalterados


In [ ]:
# Método ravel

import numpy as np

# Criar array bidimensional 4x3 de exemplo
matriz = np.array([['A','B','C'],['H','I','J'],['P','Q','R'],['X','Y','Z']])
print('Array bidimensional original:\n',matriz)

# Aplicar método ravel e criar array unidimensional do tipo view
achatadoR = matriz.ravel()

# Visualizar array achatado e original
print('\nArray achatado:',achatadoR)
print('\nArray bidimensional original:\n',matriz) # Array original não é alterado

# Alterar dados no array original e verificar se são alterados no array achatado
matriz[0,0] = 'M'
print('\nArray bidimensional original:\n',matriz) # Dado na posição 0,0 alterado
print('\nArray achatado:',achatadoR) # Dado "alterado"

## Transposição de linhas e colunas

Transpor um array significa trocar suas linhas pelas colunas e vice-versa. Podemos transpor linhas e colunas de um array de forma fácil e rápida usando o atributo **T**, o qual retorna uma view transposta do array.

In [ ]:
# Transposição de arrays

import numpy as np

matriz = np.array([['A','B','C'],['H','I','J'],['X','Y','Z']])
print('Array bidimensional original:\n',matriz)

# Efetuar transposição do array bidimensional
matrizTrans = matriz.T

print('\nMatriz transposta:\n',matrizTrans)

# Array original não é afetado pela transposição:
print('\nArray bidimensional original inalterado:\n',matriz)

## Adicionar linhas e colunas a um array: Empilhamento

Podemos combinar arrays adicionando mais linhas ou colunas, nos processos conhecidos como *empilhamento horizontal*  e *empilhamento vertical*, respectivamente.

Para tal, empregados os métodos **np.hstack** (empilhamento horizontal) e **np.vstack** (empilhamento vertical).

O empilhamento horizontal acrescenta "colunas" ao array, ao passo que o empilhamento vertical acrescenta "linhas" ao array.

In [ ]:
# Empilhamento de arrays

import numpy as np

# Criar array unidimensional
valores = np.array(['A','B','C'])
print('Array original:\n',valores)

# Array com dados a serem combinados com o array de valores
maisValores = np.array(['E','F','G'])
print('\nNovos valores:\n',maisValores)

# Acrescentar uma linha ao array (criando um array bidimensional)
dados = np.vstack((valores,maisValores)) # Parênteses internos: vstack espera receber apenas um argumento.
print('\n',dados)

# Acrescentar mais colunas (elementos) ao array original
maisValores2 = np.array(['X','Y'])
print('\n',np.hstack((valores,maisValores2))) # Parênteses internos: hstack espera receber apenas um argumento.

## Constantes NumPy

In [ ]:
# Constantes matemáticas e científicas no NumPy

import numpy as np

print('Constantes Científicas e Matemáticas do NumPy\n')

print(np.Inf)
print(np.NAN)
print(np.NINF)
print(np.NZERO)
print(np.PZERO)
print(np.pi)
print(np.e)
print(np.euler_gamma)