# NumPy

## Numerical Python

Biblioteca de código aberto criada em 2006, é extensivamente empregada para computação numérica. Escrita em linguagem C, é a implementação de estruturas de dados do tipo arrays preferida em Python, fornecendo um tipo de array de alta performance chamado de **ndarray**.

As operações sobre arrays do NumPy são até duas ordens demagnitude mais rápidas do que om o emprego de listas comuns em Python, o que certamente é uma grande vantagem quando pensamos em grandes volumes de dados a serem manipulados e analisados, por exemplo em aplicações para Big Data e Computação Numérica.

Muitas bibliotecas populares e altamente importantes dependem do NumPy para operar, como por exemplo as bibliotecas SciPy (para computação científica), Pandas (Análise de Dados) e Keras (Machine Learning / Deep Learning), entre centenas de outras bibliotecas.


## Módulo NumPy

O módulo NumPy fornece diversas funções para criação e manipulação de arrays.

In [5]:
# Criar arrays a partir de dados existentes

# Importar o módulo numpy. Recomenda-se importá-lo como "np".
import numpy as np

# Criar um array de nome "números" a partir de uma lista de valores com o método np.array()
números = np.array([4,8,16,32,64,128])

# Ver o tipo do objeto criado
print(type(números))

# Ver o conteúdo do array (valores alinhados à direita, ocupando o mesmo número de casas de acordo com o maior número presente)
print(números)

<class 'numpy.ndarray'>
[  4   8  16  32  64 128]


In [7]:
# Criar um array bidimensional a partir de uma matriz (lista de duas dimensões)

matriz = np.array([[1,4,5],[3,5,2],[5,6,0]])
print(matriz)

[[1 4 5]
 [3 5 2]
 [5 6 0]]


In [11]:
# Criar um array com os números pares de 0 a 100:
pares = np.array([n for n in range(0,101,2)])
print(pares)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [9]:
# Verificar o tipo de elemento do array: atributo dtype
números.dtype

dtype('int32')

In [14]:
# Determinar o número de dimensões de um array: atributo ndim

print(números.ndim)
print(matriz.ndim)

1
2


In [15]:
# Determinar as dimensões de um array: atributo shape (tamanho do array)

print(números.shape)
print(matriz.shape)

(6,)
(3, 3)


In [16]:
# Número total de elementos de um array: atributo size
print(números.size)
print(matriz.size)

6
9


In [17]:
# Tamanho dos elementos de um array (número de bytes necessário para armazenamento): atributo itemsize
print(números.itemsize)
print(matriz.itemsize)

4
4


In [20]:
# Iteração: iterar por um array multidimensional como se ele fosse unidimensional - atributo flat
for i in matriz.flat:
    print(i, end=' ') # end=' ' é usado para mostrar os valores em uma única linha, em vez de um por linha

1 4 5 3 5 2 5 6 0 

## Preencher arrays com valores específicos

Com as funções zeros, ones e full podemos criar arrays preenchidos automaticamente com zeros, uns ou um valor numérico especificado, respectivamente.

Os métodos zeros e ones produzem valores do tipo float64 por padrão, mas podemos alterar o tipo de dado se necessário.

In [21]:
# Criar array com 10 elementos iguais a 0
print(np.zeros(10))

# Criar array com 15 elementos iguais a 1
print(np.ones(15))

# Criar array com 8 elementos iguais a 12 (int)
print(np.full(8,12))  # primeiro argumento: núm. de elementos.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[12 12 12 12 12 12 12 12]


In [23]:
# Criar array com 10 elementos iguais a 0, tipo inteiro
print(np.zeros(10, dtype=int))

# Criar array com 15 elementos iguais a 1, tipo inteiro
print(np.ones(15, dtype=int))

# Criar array com 8 elementos iguais a 12, tipo ponto flutuante
print(np.full(8,12, dtype=float))  # primeiro argumento: núm. de elementos.

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[12. 12. 12. 12. 12. 12. 12. 12.]


In [28]:
# Criar array bidimensional 2x5 preenchido com zeros, tipo inteiro:
print(np.zeros((2, 5),dtype=int))

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [37]:
# Criar array a partir de faixas de valores: método arange

# Array de 10 elementos, números de 0 a 9
print(np.arange(10))

# Array de 10 elementos float, números de 0 a 9
print(np.arange(10.))

# Array com valores no intervalo de 5 a 15
print(np.arange(5,16))

# Array com os números pares de 50 até 1
print(np.arange(50, 1, -2))

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 5  6  7  8  9 10 11 12 13 14 15]
[50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10  8  6  4
  2]


In [35]:
# Criar array com valores de ponto flutuante com o método linspace

print(np.linspace(0.0,2.0,num=5))
# primeiro argumento: valor inicial
# segundo argumento: valor final
# terceiro argumento (num): quantidade de itens a gerar

[0.  0.5 1.  1.5 2. ]


In [40]:
# Criar array unidimensional e transformá-lo em bidimensional: método reshape
print(np.arange(10,50,2).reshape(5,4)) # array 5x4

[[10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]]


## Verificar performance de arrays NumPy vs listas

Usando o comando **%timeit magic** do IPython, que contabiliza a duração média de operações.

In [42]:
# Medir tempo para criação de uma lista comum com 10 milhões de itens
import random

%timeit teste = [random.randrange(1,10) for i in range(0, 10000000)]

10.3 s ± 183 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [43]:
# Medir tempo para criação de um array NumPy com 10 milhões de itens
import numpy as np

%timeit teste = np.random.randint(1,10,10000000)

153 ms ± 15.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [50]:
# Medir tempo para criação e soma de valores de uma lista comum com 5 milhões de itens

%timeit sum([n for n in range(5000000)])

439 ms ± 31.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [51]:
# Medir tempo para criação e soma de valores de um array NumPy com 5 milhões de itens

%timeit np.arange(5000000).sum()

11.5 ms ± 1.27 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Operações aritméticas com arrays

É possível realizar diversas operações aritméticas sobre arrays, com o emprego de operadores variados. Vamos estudar aritmética simples com alguns exemplos de operações entre arrays e valores escalares, e entre arrays de mesmas dimensões.

Iniciamos criando um array para testes, de nome valores, contendo números de 1 a 10.

In [52]:
import numpy as np

valores = np.arange(1,11)
print(valores)

[ 1  2  3  4  5  6  7  8  9 10]


In [54]:
# Vamos realizar operações aritméticas com os valores do array: multiplicação e exponenciação

print(valores * 5)
print(valores ** 3)

# As operações são efetuadas para cada valor presente no array, individualmente. Essa operação se chama broadcasting.
# O array em si permanece inalterado:
print(valores)

# Porém é modificado por operações cumulativas, como incremento:
valores += 10
print(valores)

[ 5 10 15 20 25 30 35 40 45 50]
[   1    8   27   64  125  216  343  512  729 1000]
[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


### Operações aritméticas entre arrays

É possível efetuar operações aritméticas entre arrays que tenham as mesmas dimensões (shape). Por exemplo, vamos efetuar a multiplicação entre dois arrays unidimensionais de 4 elementos cada.

O resultado será um novo array formado pela multiplicação de cada elemento no primeiro array pelo elemento na posição correspondente no segundo array:

In [55]:
# Multiplicação de arrays

val1 = np.array([2,4,6,8])
val2 = np.array([1,2,3,4])

print(val1 * val2)

[ 2  8 18 32]


### Efetuar operações matemáticas comuns

Podemos também efetuar diversas operações matemáticas comuns sobre os elementos de um array, como determinar o maior e menor valor, somatório, média, valores estatísticos, etc.

Considere o seguinte exemplo:

In [57]:
# Aplicando funções sobre um array

val = np.array([2,4,5,6,8,10,11])

# Somatório do array
print(val.sum())

# Média aritmética dos valores do array
print(val.mean())

# Maior valor presente no array
print(val.max())

# Menor valor presente no array
print(val.min())

# Desvio-padrão do array
print(val.std())

# Variância do array
print(val.var())

46
6.571428571428571
11
2
3.0169588688489823
9.102040816326532


## Operações em linhas ou colunas

É possível efetuar operações em linhas ou colunas inteiras de um array multidimensional, bastando para isso especificar o eixo desejado por meio do parâmetro *axis*.

O valor 0 em axis representa colunas, ao passo que o valor 1 indica linhas.

Como exemplo, vamos considerar uma tabela de valores bidimensional como a que segue:

2 3 6
3 5 7
2 4 7
2 7 8

Desejamos conhecer o somatório de cada linha individual, e o valor médio de cada coluna. Para isso, faremos da seguinte forma:


In [3]:
import numpy as np

matriz = np.array([[2,3,6],[3,5,7],[2,4,7],[2,7,8]])
print(matriz)

# Somatório de cada linha
print(matriz.sum(axis=1))

# Média aritmética de cada coluna
print(matriz.mean(axis=0))

[[2 3 6]
 [3 5 7]
 [2 4 7]
 [2 7 8]]
[11 15 13 17]
[2.25 4.75 7.  ]


## Calcular raiz Quadrada dos Elementos de um array

Podemos calcular a raiz quadrada de cada elemento de um array usando uma função universal, que é aplicada a cada elemento individualmente.

A função para cálculo de raiz quadrada é a função np.sqrt()

Vamos ao exemplo.

In [11]:
# Calcular a raiz quadrada de cada elemento de um array

import numpy as np

valores = np.arange(10,101,5)  # números de 10 a 100, de 5 em 5
print(valores)

# Raiz de cada elemento do array:
print(np.sqrt(valores))

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]
[ 3.16227766  3.87298335  4.47213595  5.          5.47722558  5.91607978
  6.32455532  6.70820393  7.07106781  7.41619849  7.74596669  8.06225775
  8.36660027  8.66025404  8.94427191  9.21954446  9.48683298  9.74679434
 10.        ]


## Soma de arrays

De forma análoga, podemos somar dois arrays de mesma dimensão usando uma função universal: a função np.add().

Vejamos um exemplo.

In [13]:
# Soma de arrays com função np.add()
import numpy as np

# Criar os dois arrays
val1 = np.arange(10,21)
print(val1)
val2 = np.arange(40,51)
print(val2)

# Relizar a soma e exibir o resultado
res = np.add(val1, val2)
print(res)


[10 11 12 13 14 15 16 17 18 19 20]
[40 41 42 43 44 45 46 47 48 49 50]
[50 52 54 56 58 60 62 64 66 68 70]


## Outras funções universais do NumPy

A biblioteca NumPy possui diversas funções universais disponíveis. Algumas delas estão listadas a seguir:

- Funções matemáticas: add, subtract, multiply, divide, remainder, exp, log, power
- Funções trigonométricas: sin, cos, tan, hypot, arcsin, arccos, arctan
- Manipulação de bits: bitwise_and, bitwise_or, bitwise_xor, invert, left_shift, right_shift
- Comparação: greater, greater_equal, less, less_equal, equal, not_equal, logical_and, logical_or, logical_xor, logical_not, minimum, maximum
- Ponto flutuante: floor, ceil, isinf, isnan, fabs, trunc


## Indexação e Fatiamento de arrays

MIMIMIMI

In [6]:
# Indexação e fatiamento de arrays unidimensionais (inicia indexação de zero)

import numpy as np

valores = np.array([2,5,8,0,12,9,11,5,7])
print(valores) # Mostra o array inteiro
print(valores[0]) # Primeiro elemento do array (índice 0)
print(valores[-1]) # Último elemento do array (índice -1)
print(valores[:3]) # três primeiros elementos do array
print(valores[2:5]) # do segundo ao quarto elemento (5 - 1), ou ainda, três elementos a partir do segundo (5 - 2)
print(valores[4:]) # Do quarto elemento até o final do array

[ 2  5  8  0 12  9 11  5  7]
2
7
[2 5 8]
[ 8  0 12]
[12  9 11  5  7]


In [18]:
# Indexação e fatiamento de arrays bidimensionais (inicia indexação de zero)

import numpy as np

matriz = np.array([[3,5,7],[1,0,5],[7,2,8]])
print(matriz)

print(matriz[0,0]) # Mostrar elemento da primeira linha, primeira coluna
print(matriz[2,1]) # Mostrar elemento da linha 2, coluna 1
print(matriz[1]) # Linha 1 inteira 
print(matriz[0:2]) # Linhas 0 e 1
print(matriz[[0,2]]) # Linhas 0 e 2 - usar lista de índices
print(matriz[:,1]) # Coluna 1 inteira 
print(matriz[:,1:]) # Colunas 1 e 2 inteiras com fatiamento ou
print(matriz[:,[1,2]]) # Colunas 1 e 2 inteiras usando lista de colunas

[[3 5 7]
 [1 0 5]
 [7 2 8]]
3
2
[1 0 5]
[[3 5 7]
 [1 0 5]]
[[3 5 7]
 [7 2 8]]
[5 0 2]
[[5 7]
 [0 5]
 [2 8]]
[[5 7]
 [0 5]
 [2 8]]


## Views: Shallow Copies e Deep Copies

In [ ]:
# MIMIMI