## Objeto Matrix - Matrizes

Os objetos do tipo matrix (matriz) em NumPy herdam do objeto ndarray, sendo portanto uma subclasse e, assim, possuem os mesmos atributos e métodos que sua superclasse. São um array 2-D especializado.

Porém, existem diferenças entre objetos matrix e arrays em NumPy:

- Objetos matrix podem ser criados usando uma sintaxe no estilo Matlab, com espaços separando colunas e ponto-e-vírgula ; separando linhas
- As matrizes são sempre bidimensionais, ao passo que os arrays podem ter n dimensões
- A multiplicação de objetos matrix equivale à multiplicação matemática de matrizes, assim como a exponenciação, usando os operadores * e ** respectivamente.
- Operações mistas entre matrizes e ndarrays sempre produzem matrizes
- As matrizes possuem atributos especiais que facilitam determinados cálculos, tais como:
    - matriz.T - Transposta
    - matriz.H - Transposta Hermitiana
    - matriz.I - Inversa
    - martiz.A - array-base
    
Usamos comumente o nome mat como alias para matrizes no NumPy.

Vamos criar matrizes de exemplo.

In [6]:
# Criar uma matriz com o método matrix()

import numpy as np

# Estilo NumPy (Python)
a = np.matrix([[1,2,3],[4,5,6]])

# Estilo Matlab
b = np.matrix('1 2 3 ; 4 5 6')

print('Matriz a:\n', a)
print(type(a))

print('\nMatriz b:\n', b)
print(type(b))

Matriz a:
 [[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>

Matriz b:
 [[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


Vamos criar dois objetos: uma matriz e um ndarray com duas dimensões, e realizar multiplicações entre os objetos para comparar os resultados.
M será a matriz, e A será o array, e ambo possuem exatamente os mesmos valores para comparação:

In [13]:
import numpy as np

# Criar Matriz
M = np.matrix([[1,2],[4,5]])
print('Matriz M:\n', M)
print(type(M))

# Criar Array de duas dimensões
A = np.array([[1,2],[4,5]])
print('\nArray A:\n', A)
print(type(A))

# Efetuar as mutiplicações
# 1. Matriz x Matriz:
print('\nMatriz M vezes matriz M:')
print(M * M)

# 2. Matriz x Array
print('\nMatriz M vezes array A:') # Resultado é matriz
print(M * A)

# 3. Array x Array
print('\nArray A vezes array A:')
print(A * A)

Matriz M:
 [[1 2]
 [4 5]]
<class 'numpy.matrix'>

Array A:
 [[1 2]
 [4 5]]
<class 'numpy.ndarray'>

Matriz M vezes matriz M:
[[ 9 12]
 [24 33]]

Matriz M vezes array A:
[[ 9 12]
 [24 33]]

Array A vezes array A:
[[ 1  4]
 [16 25]]


## Métodos de matrizes

pg. 112 do NumPy Reference